import test from 'node:test';
import assert from 'node:assert/strict';
import {createConversationFixture,launchQualifiedBrowser,openConversationPage,conversationMenu,closeConversationHarness,assertBrowserContained,assertNoPrivatePersistence,writeSyntheticEvidence,RELAY_URL,OWNER_KEY} from './helpers/relay-conversation-browser-fixture.js';
import {RELAY_OWNER_INBOX} from '../backend/relay-common.js';

test('private work filters use loaded records and explicit detail preserves truthful progress and corrected results', {timeout:120000},async t=>{
  const browser=await launchQualifiedBrowser(t);if(!browser)return;const h=createConversationFixture(t),pages=[];
  try{
    const auth=await h.oauth(),owner=await h.pair(auth),rpc=(name,args)=>h.rpc(auth,name,{inbox_id:RELAY_OWNER_INBOX,...args});
    async function create(title,labels=true){const response=await h.phone('/jobs',{id:crypto.randomUUID(),title,body:'Fictional private task: '+title,action_kind:'read_only',...(labels?{project_title:'Fictional garden',goal_title:'Plan a quiet path'}:{})},owner.device_token);assert.equal(response.status,201);return (await response.json()).job;}
    const queued=await create('Compare path materials'),working=await create('Check the two source notes'),blocked=await create('Confirm the path width'),done=await create('Draft the planting list'),unverified=await create('An old acknowledgement',false);
    const workingRun=crypto.randomUUID();await rpc('relay_owner_job_claim',{job_id:working.id,run_id:workingRun,event_id:crypto.randomUUID()});await rpc('relay_owner_job_update',{job_id:working.id,run_id:workingRun,event_id:crypto.randomUUID(),stage:'running',summary:'Read both fictional notes; checking the measurements.'});
    const blockedRun=crypto.randomUUID();await rpc('relay_owner_job_claim',{job_id:blocked.id,run_id:blockedRun,event_id:crypto.randomUUID()});await rpc('relay_owner_job_update',{job_id:blocked.id,run_id:blockedRun,event_id:crypto.randomUUID(),stage:'waiting_for_owner',summary:'Which fictional width should the path use?',outcome:'not_started'});
    const doneRun=crypto.randomUUID();await rpc('relay_owner_job_claim',{job_id:done.id,run_id:doneRun,event_id:crypto.randomUUID()});const reply=await rpc('relay_owner_reply',{message_id:done.id,body:'Fictional original list: three shrubs.'});await rpc('relay_owner_job_update',{job_id:done.id,run_id:doneRun,event_id:crypto.randomUUID(),stage:'completed',summary:'Checked and prepared the fictional planting list.',outcome:'known',expected_reply_id:reply.entry.id,expected_version:1});await rpc('relay_owner_job_result_correct',{job_id:done.id,event_id:crypto.randomUUID(),expected_reply_id:reply.entry.id,expected_version:1,body:'Fictional corrected list: four shrubs. https://example.test/fictional-source',correction_summary:'Checked the fictional second note; corrected the count.'});
    await rpc('relay_owner_reply',{message_id:unverified.id,body:'Fictional acknowledgement: I received this.'});
    const phone=await openConversationPage(browser,h,{owner,clock:false});pages.push(phone);const page=phone.page;
    await page.goto(RELAY_URL);await page.locator('[data-job-id="'+working.id+'"]').waitFor();
    const before=phone.records.filter(r=>r.method==='GET'&&r.path.startsWith('/relay/owner/')).length,beforeAll=phone.records.filter(r=>r.path.startsWith('/relay/owner/')).length;
    const detailReads=()=>phone.records.filter(r=>r.method==='GET'&&r.path.endsWith('/jobs/detail'));
    await conversationMenu(page,'Requests');const work=page.locator('#relay-owner-current-work');await work.waitFor();
    assert.equal(await work.locator('[data-job-id="'+queued.id+'"]').getAttribute('data-state'),'queued');
    assert.equal(await work.locator('[data-job-id="'+working.id+'"]').getAttribute('data-state'),'working');
    assert.equal(await work.locator('[data-job-id="'+blocked.id+'"]').getAttribute('data-attention'),'waiting_for_owner');
    assert.equal(await work.locator('[data-job-id="'+unverified.id+'"]').getAttribute('data-attention'),'completion_unverified');
    const filter=work.locator('#relay-owner-work-filter'),rows=work.locator('button[data-job-id]');
    assert.match(await filter.innerText(),/Waiting for you · 1/);assert.match(await filter.innerText(),/Finish not confirmed · 1/);
    await filter.selectOption('waiting_for_owner');assert.equal(await rows.count(),1);assert.equal(await rows.first().getAttribute('data-job-id'),blocked.id);
    await filter.selectOption('all');await conversationMenu(page,'Search current work');const search=page.getByRole('searchbox',{name:'Search current work'});
    await search.fill('measurements');assert.equal(await rows.count(),1);assert.equal(await rows.first().getAttribute('data-job-id'),working.id);
    await filter.selectOption('queued');assert.equal(await rows.count(),0);assert.match(await work.innerText(),/No work matches this search and status/);
    await search.fill('');assert.equal(await rows.count(),1);assert.equal(await rows.first().getAttribute('data-job-id'),queued.id);
    await filter.selectOption('finished');await search.fill('four shrubs');assert.equal(await rows.count(),1);assert.equal(await rows.first().getAttribute('data-job-id'),done.id);
    await filter.selectOption('all');await page.getByRole('button',{name:'Close search',exact:true}).click();assert.equal(await rows.count(),5);
    assert.equal(phone.records.filter(r=>r.method==='GET'&&r.path.startsWith('/relay/owner/')).length,before,'Navigation, local search and every filter use loaded records');
    assert.equal(phone.records.filter(r=>r.path.startsWith('/relay/owner/')).length,beforeAll,'Local controls add no preflight request');assert.equal(detailReads().length,0);
    for(const size of [{width:360,height:800},{width:390,height:844},{width:390,height:520}]){
      await page.setViewportSize(size);const geometry=await page.evaluate(()=>({viewport:innerWidth,width:document.documentElement.scrollWidth}));assert.ok(geometry.width<=geometry.viewport,JSON.stringify({size,geometry}));const targets=await work.locator('button:visible,select:visible').evaluateAll(nodes=>nodes.map(n=>({height:n.getBoundingClientRect().height,width:n.getBoundingClientRect().width})));assert.ok(targets.every(n=>n.height>=48&&n.width>=48),JSON.stringify({size,targets}));await writeSyntheticEvidence(phone,'private-current-work-'+size.width+'x'+size.height,{synthetic:true,localRequests:0,geometry});
    }
    const current=work.locator('[data-job-id="'+working.id+'"]');await current.click();await page.waitForFunction(()=>{const b=document.querySelector('#relay-owner-request-refresh');return b&&!b.disabled;});await page.locator('#relay-owner-latest-progress').waitFor();assert.match(await page.locator('#relay-owner-latest-progress').innerText(),/Read both fictional notes/);assert.equal(detailReads().length,1);
    await page.getByRole('button',{name:'Back from task',exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement.dataset.jobId),working.id,'Back restores the selected task');
    await work.locator('[data-job-id="'+blocked.id+'"]').click();await page.getByRole('button',{name:'Reply in chat',exact:true}).waitFor();assert.match(await page.locator('#relay-owner-latest-progress').innerText(),/Which fictional width/);await page.getByRole('button',{name:'Back from task',exact:true}).click();
    await work.locator('[data-job-id="'+done.id+'"]').click();await page.waitForFunction(()=>{const b=document.querySelector('#relay-owner-request-refresh');return b&&!b.disabled;});const detail=page.locator('#relay-owner-request-dialog');await detail.locator('#relay-owner-result-latest').waitFor();assert.equal(await detail.locator('#relay-owner-result-latest').getAttribute('data-result-version'),'2');assert.match(await detail.locator('#relay-owner-result-latest').innerText(),/four shrubs/);assert.equal(await detail.locator('#relay-owner-completion').getAttribute('data-result-version'),'1');
    await detail.locator('#relay-owner-request-history>summary').click();await detail.locator('#relay-owner-result-history>summary').click();assert.match(await detail.locator('#relay-owner-result-history').innerText(),/three shrubs/);assert.match(await detail.locator('#relay-owner-result-history').innerText(),/four shrubs/);await detail.locator('#relay-owner-request-properties>summary').click();assert.match(await detail.locator('#relay-owner-request-properties').innerText(),/does not certify factual claims or external outcomes/);await page.getByRole('button',{name:'Back from task',exact:true}).click();
    await conversationMenu(page,'Search current work');await search.fill('four shrubs');await filter.selectOption('finished');const readsBeforeRefresh=detailReads().length;
    const refreshed=page.waitForResponse(r=>r.request().method()==='GET'&&new URL(r.url()).pathname.endsWith('/jobs/changes')&&r.ok());await conversationMenu(page,'Refresh private inbox');await refreshed;await page.waitForFunction(()=>!document.querySelector('#relay-owner-message-form [role=status]')?.textContent.includes('Refreshing'));assert.equal(await search.inputValue(),'four shrubs');assert.equal(await filter.inputValue(),'finished');assert.equal(await rows.count(),1);assert.equal(detailReads().length,readsBeforeRefresh,'Ordinary refresh does not eagerly inspect tasks');
    await page.reload();await page.locator('[data-job-id="'+done.id+'"]').waitFor();await conversationMenu(page,'Requests');await page.locator('#relay-owner-current-work [data-job-id="'+done.id+'"]').click();await page.locator('#relay-owner-result-latest').waitFor();assert.match(await page.locator('#relay-owner-result-latest').innerText(),/four shrubs/);await page.getByRole('button',{name:'Back from task',exact:true}).click();
    await conversationMenu(page,'Public chat');assert.equal(await page.locator('#relay-owner-current-work:visible').count(),0);assert.equal((await page.locator('body').innerText()).includes('Fictional garden'),false);
    assertBrowserContained(phone);await assertNoPrivatePersistence(page,['Fictional garden','Fictional private task','four shrubs']);
  }finally{await closeConversationHarness(browser,h,pages);}
});


test('phone work rows wrap and preserve focused reading through heartbeat and new saved activity', {timeout:120000},async t=>{
  const browser=await launchQualifiedBrowser(t);if(!browser)return;const h=createConversationFixture(t),pages=[];
  try{
    const auth=await h.oauth(),owner=await h.pair(auth),rpc=(name,args)=>h.rpc(auth,name,{inbox_id:RELAY_OWNER_INBOX,...args}),jobs=[];
    const long='FictionalLongProjectLabel'.repeat(5).slice(0,120);
    for(let i=0;i<12;i++){const response=await h.phone('/jobs',{id:crypto.randomUUID(),title:(i===0?'FictionalLongTaskTitle'.repeat(6).slice(0,120):'Fictional task '+i),body:'Fictional private reading fixture.',action_kind:'read_only',project_title:long,goal_title:long},owner.device_token);assert.equal(response.status,201);jobs.push((await response.json()).job);}
    const target=jobs[4],run=crypto.randomUUID();await rpc('relay_owner_job_claim',{job_id:target.id,run_id:run,event_id:crypto.randomUUID()});await rpc('relay_owner_job_update',{job_id:target.id,run_id:run,event_id:crypto.randomUUID(),stage:'running',summary:'Compared both fictional notes; one measurement still needs checking.'});
    const phone=await openConversationPage(browser,h,{owner,width:360,height:800});pages.push(phone);const page=phone.page;
    await page.goto(RELAY_URL);await page.locator('[data-job-id="'+target.id+'"]').waitFor();await conversationMenu(page,'Requests');const work=page.locator('#relay-owner-current-work'),current=work.locator('[data-job-id="'+target.id+'"]');
    const row=work.locator('[data-job-id="'+jobs[0].id+'"]');await row.scrollIntoViewIfNeeded();const geometry=await row.evaluate(n=>({width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height,scroll:n.scrollWidth}));assert.ok(geometry.height>=48&&geometry.scroll<=geometry.width+1,JSON.stringify(geometry));
    // Keep a queued task in view while a different task's lease is renewed.
    await row.evaluate(n=>{const panel=n.closest('.messages');panel.scrollTop+=n.getBoundingClientRect().top-panel.getBoundingClientRect().top-24;n.focus({preventScroll:true});});
    const before=await row.evaluate(n=>({offset:n.getBoundingClientRect().top-n.closest('.messages').getBoundingClientRect().top,id:n.id})),activity=await current.locator('.job-state').innerText(),order=await work.locator('button[data-job-id]').evaluateAll(nodes=>nodes.map(n=>n.dataset.jobId));
    await rpc('relay_owner_job_update',{job_id:target.id,run_id:run,event_id:crypto.randomUUID(),stage:'running'});
    let response=page.waitForResponse(r=>r.request().method()==='GET'&&new URL(r.url()).pathname.endsWith('/jobs/changes')&&r.status()===200);await page.clock.fastForward(30000);await response;await page.waitForFunction(()=>!document.querySelector('#relay-owner-message-form [role=status]')?.textContent.includes('Refreshing'));
    assert.deepEqual(await work.locator('button[data-job-id]').evaluateAll(nodes=>nodes.map(n=>n.dataset.jobId)),order,'A heartbeat cannot reorder work');assert.equal(await current.locator('.job-state').innerText(),activity,'A heartbeat cannot manufacture visible progress');
    assert.equal(await page.evaluate(()=>document.activeElement.id),before.id);assert.ok(Math.abs((await row.evaluate(n=>n.getBoundingClientRect().top-n.closest('.messages').getBoundingClientRect().top))-before.offset)<=1,'Focused reading anchor survives the existing refresh');
    const other=jobs[9],otherRun=crypto.randomUUID();await rpc('relay_owner_job_claim',{job_id:other.id,run_id:otherRun,event_id:crypto.randomUUID()});await rpc('relay_owner_job_update',{job_id:other.id,run_id:otherRun,event_id:crypto.randomUUID(),stage:'running',summary:'Fictional meaningful activity with enough details to wrap across several lines on the narrow phone screen.'});
    response=page.waitForResponse(r=>r.request().method()==='GET'&&new URL(r.url()).pathname.endsWith('/jobs/changes')&&r.status()===200);await page.clock.fastForward(30000);await response;await page.waitForFunction(()=>!document.querySelector('#relay-owner-message-form [role=status]')?.textContent.includes('Refreshing'));
    assert.equal(await page.evaluate(()=>document.activeElement.id),before.id);assert.ok(Math.abs((await row.evaluate(n=>n.getBoundingClientRect().top-n.closest('.messages').getBoundingClientRect().top))-before.offset)<=1,'New activity above the focused task preserves its reading position');
    for(const size of [{width:360,height:800},{width:390,height:844},{width:390,height:520}]){await page.setViewportSize(size);const bounds=await page.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth,bottom:document.querySelector('#relay-owner-message-form').getBoundingClientRect().bottom}));assert.ok(bounds.width<=size.width&&bounds.bottom<=size.height+1,JSON.stringify({size,bounds}));}
    assert.equal(phone.records.filter(r=>r.path.endsWith('/jobs/detail')).length,0);assertBrowserContained(phone);await assertNoPrivatePersistence(page,['FictionalLongProjectLabel','Fictional meaningful activity']);
    await writeSyntheticEvidence(phone,'private-work-reading-anchor',{synthetic:true,focusPreserved:true,readingAnchorTolerance:1,heartbeatReordered:false,heartbeatAdvancedActivity:false});
  }finally{await closeConversationHarness(browser,h,pages);}
});


test('authorization loss while private work is public and unmounted clears search, filters and task editor state', {timeout:120000},async t=>{
  const browser=await launchQualifiedBrowser(t);if(!browser)return;const h=createConversationFixture(t),pages=[];
  try{
    const auth=await h.oauth(),owner=await h.pair(auth),project='Fictional prior private project';
    const response=await h.phone('/jobs',{id:crypto.randomUUID(),title:'Fictional private task',body:'Fictional private scope.',action_kind:'read_only',project_title:project},owner.device_token);assert.equal(response.status,201);const job=(await response.json()).job;
    const phone=await openConversationPage(browser,h,{owner,clock:false});pages.push(phone);const page=phone.page;
    await page.goto(RELAY_URL);await page.locator('[data-job-id="'+job.id+'"]').waitFor();await conversationMenu(page,'Requests');await page.locator('#relay-owner-new-task').click();await page.locator('.owner-job-organization>summary').click();await page.locator('#relay-owner-job-project').fill(project);await page.locator('#relay-owner-task-back').click();await conversationMenu(page,'Search current work');const search=page.getByRole('searchbox',{name:'Search current work'});await search.fill(project);
    await page.locator('#relay-owner-work-filter').selectOption('queued');await search.fill('prior private project');
    await conversationMenu(page,'Public chat');assert.equal(await page.locator('#relay-owner-current-work').count(),0,'The private UI is unmounted while showing public chat');
    await page.evaluate(key=>{localStorage.removeItem(key);dispatchEvent(new StorageEvent('storage',{key,newValue:null,storageArea:localStorage}));},OWNER_KEY);
    const replacement=await h.pair(auth,'Fictional replacement session');const value=JSON.stringify({device_token:replacement.device_token,device_id:replacement.device.id});
    await page.evaluate(({key,value})=>{localStorage.setItem(key,value);dispatchEvent(new StorageEvent('storage',{key,newValue:value,storageArea:localStorage}));},{key:OWNER_KEY,value});
    await conversationMenu(page,'Owner chat');await page.locator('[data-job-id="'+job.id+'"]').waitFor();assert.equal(await page.locator('#relay-owner-search').inputValue(),'','The old private search is not restored into the replacement session');
    assert.equal(await page.locator('#relay-owner-job-project').inputValue(),'');assert.equal(await page.locator('#relay-owner-job-goal').inputValue(),'');assert.equal(await page.locator('.owner-job-fields').isVisible(),false,'Private composer prefills do not enter the replacement session');
    await conversationMenu(page,'Requests');const restored=page.locator('#relay-owner-current-work');assert.equal(await page.locator('#relay-owner-work-filter').inputValue(),'all','Authorization loss resets private local filters even while unmounted/public');
    assert.match(await restored.innerText(),/Fictional private task/);assertBrowserContained(phone);await assertNoPrivatePersistence(page,[project,'prior private project']);
  }finally{await closeConversationHarness(browser,h,pages);}
});

test('New task retains editable scope and labels without submitting or replacing drafts', {timeout:120000},async t=>{
  const browser=await launchQualifiedBrowser(t);if(!browser)return;const h=createConversationFixture(t),pages=[];
  try{
    const auth=await h.oauth(),owner=await h.pair(auth),project='FictionalLongProjectLabel'.repeat(5).slice(0,120),goal='FictionalLongGoalLabel'.repeat(5).slice(0,120);
    const response=await h.phone('/jobs',{id:crypto.randomUUID(),title:'Fictional existing task',body:'Fictional existing private work',action_kind:'read_only',project_title:project,goal_title:goal},owner.device_token);assert.equal(response.status,201);const original=(await response.json()).job;
    const phone=await openConversationPage(browser,h,{owner,clock:false,width:360,height:800});pages.push(phone);const page=phone.page;
    await page.goto(RELAY_URL);await page.locator('[data-job-id="'+original.id+'"]').waitFor();await conversationMenu(page,'Requests');const work=page.locator('#relay-owner-current-work');
    await conversationMenu(page,'Search current work');const search=page.locator('#relay-owner-search');await search.fill('fictionallong');await work.locator('#relay-owner-work-filter').selectOption('queued');
    const before=phone.records.length;await page.locator('#relay-owner-new-task').click();
    assert.equal(await page.locator('#relay-owner-job-project').inputValue(),'');assert.equal(await page.locator('#relay-owner-job-goal').inputValue(),'');await page.locator('.owner-job-organization>summary').click();await page.locator('#relay-owner-job-project').fill(project);assert.equal(await page.evaluate(()=>document.activeElement.id),'relay-owner-job-project');assert.equal(await page.locator('#relay-owner-job-kind').inputValue(),'consequential');
    await page.locator('#relay-owner-job-goal').fill(goal);await page.locator('#relay-owner-job-kind').selectOption('draft');await page.locator('#relay-owner-task-back').click();await page.locator('#relay-owner-new-task').press('Enter');
    assert.equal(await page.locator('#relay-owner-job-project').inputValue(),project);assert.equal(await page.locator('#relay-owner-job-goal').inputValue(),goal);assert.equal(await page.locator('#relay-owner-job-kind').inputValue(),'draft');assert.equal(await page.evaluate(()=>document.activeElement.id),'relay-owner-job-title');
    assert.equal(await search.inputValue(),'fictionallong');assert.equal(await work.locator('#relay-owner-work-filter').inputValue(),'queued');
    assert.equal(phone.records.slice(before).filter(r=>r.path.startsWith('/relay/owner/')).length,0,'Opening and editing prefills creates no API or preflight request');
    for(const size of [{width:360,height:800},{width:390,height:844},{width:390,height:520}]){
      await page.setViewportSize(size);await page.locator('#relay-owner-job-title').scrollIntoViewIfNeeded();const geometry=await page.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth,composer:document.querySelector('#relay-owner-message-form').getBoundingClientRect().toJSON(),title:document.querySelector('#relay-owner-job-title').getBoundingClientRect().toJSON()}));
      assert.ok(geometry.width<=size.width&&geometry.composer.bottom<=size.height+1&&geometry.title.top>=0,JSON.stringify({size,geometry}));
      const targets=await page.locator('#relay-owner-message-form input:visible,#relay-owner-message-form select:visible,#relay-owner-message-form summary:visible,#relay-owner-message-form button:visible,.owner-work-add-task:visible').evaluateAll(nodes=>nodes.map(n=>({tag:n.tagName,width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height})));assert.ok(targets.every(n=>n.width>=48&&n.height>=48),JSON.stringify({size,targets}));
      await writeSyntheticEvidence(phone,'private-add-task-'+size.width+'x'+size.height,{synthetic:true,openingRequests:0,geometry});
    }
    await page.locator('#relay-owner-job-project').fill('Fictional edited project');await page.locator('#relay-owner-job-goal').fill('Fictional edited goal');await page.locator('#relay-owner-job-title').fill('Fictional submitted task');await page.locator('#relay-owner-message-text').fill('Fictional explicit task body');
    await page.locator('#relay-owner-task-back').click();await page.locator('#relay-owner-new-task').click();assert.equal(await page.locator('#relay-owner-job-project').inputValue(),'Fictional edited project');assert.equal(await page.locator('#relay-owner-job-goal').inputValue(),'Fictional edited goal');assert.equal(await page.locator('#relay-owner-job-title').inputValue(),'Fictional submitted task');assert.equal(await page.locator('#relay-owner-message-text').inputValue(),'Fictional explicit task body');assert.equal(await page.evaluate(()=>document.activeElement.id),'relay-owner-job-title','Resume returns to the existing task draft');
    assert.equal(phone.records.filter(r=>r.method==='POST'&&r.path==='/relay/owner/jobs').length,0);
    const submitted=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/relay/owner/jobs'&&r.status()===201);await page.getByRole('button',{name:'Send private request',exact:true}).click();await submitted;await page.waitForFunction(()=>document.querySelector('#relay-owner-message-form [role=status]')?.textContent==='Work request saved');
    const posts=phone.records.filter(r=>r.method==='POST'&&r.path==='/relay/owner/jobs');assert.equal(posts.length,1);const payload=JSON.parse(posts[0].body);assert.equal(payload.project_title,'Fictional edited project');assert.equal(payload.goal_title,'Fictional edited goal');assert.equal(payload.action_kind,'draft');assert.equal(payload.title,'Fictional submitted task');assert.equal(payload.body,'Fictional explicit task body');assert.equal(h.rows('SELECT COUNT(*) AS n FROM relay_owner_jobs')[0].n,2);
    assert.equal(await search.inputValue(),'fictionallong');assert.equal(await work.locator('#relay-owner-work-filter').inputValue(),'queued');assert.equal(await work.locator('button[data-job-id]').count(),1,'The new task can remain hidden by the preserved search while its save is acknowledged');
    await conversationMenu(page,'Public chat');assert.equal(await page.locator('.owner-work-add-task:visible').count(),0);assert.equal((await page.locator('body').innerText()).includes(project),false);assertBrowserContained(phone);await assertNoPrivatePersistence(page,[project,goal,'Fictional submitted task','Fictional explicit task body']);
  }finally{await closeConversationHarness(browser,h,pages);}
});

test('New task exposes the original send retry after the owner clears an unconfirmed task', {timeout:120000},async t=>{
  const browser=await launchQualifiedBrowser(t);if(!browser)return;const h=createConversationFixture(t),pages=[];
  try{
    const auth=await h.oauth(),owner=await h.pair(auth),project='Fictional retry project',goal='Fictional retry goal';
    const response=await h.phone('/jobs',{id:crypto.randomUUID(),title:'Fictional existing task',body:'Fictional prior work.',action_kind:'read_only',project_title:project,goal_title:goal},owner.device_token);assert.equal(response.status,201);const original=(await response.json()).job;
    const phone=await openConversationPage(browser,h,{owner,clock:false,width:390,height:520});pages.push(phone);const page=phone.page;
    await page.goto(RELAY_URL);await page.locator('[data-job-id="'+original.id+'"]').waitFor();await conversationMenu(page,'Requests');
    const add=page.locator('#relay-owner-new-task');await add.click();await page.locator('.owner-job-organization>summary').click();await page.locator('#relay-owner-job-project').fill(project);await page.locator('#relay-owner-job-goal').fill(goal);await page.locator('#relay-owner-job-kind').selectOption('draft');await page.locator('#relay-owner-job-title').fill('Fictional uncertain task');await page.locator('#relay-owner-message-text').fill('Fictional uncertain task body');
    phone.rule(record=>record.method==='POST'&&record.path==='/relay/owner/jobs',async({forward})=>{const accepted=await forward();assert.equal(accepted.status,201);return {abort:true};});
    await page.getByRole('button',{name:'Send private request',exact:true}).click();await page.getByRole('button',{name:'Retry private send',exact:true}).waitFor();
    const writes=()=>phone.records.filter(record=>record.method==='POST'&&record.path==='/relay/owner/jobs');assert.equal(writes().length,1);const accepted=JSON.parse(writes()[0].body);assert.equal(h.rows('SELECT COUNT(*) AS n FROM relay_owner_jobs')[0].n,2);
    await page.locator('#relay-owner-job-title').fill('');await page.locator('#relay-owner-job-project').fill('');await page.locator('#relay-owner-job-goal').fill('');await page.locator('#relay-owner-message-text').fill('');await page.getByRole('button',{name:'Switch to private message',exact:true}).click();
    const refreshed=page.waitForResponse(r=>r.request().method()==='GET'&&new URL(r.url()).pathname.endsWith('/jobs/changes')&&r.ok());await conversationMenu(page,'Refresh private inbox');await refreshed;await page.waitForFunction(()=>document.querySelector('#relay-owner-message-form [role=status]')?.textContent.includes('Send unconfirmed'));
    const before=phone.records.length;await add.click();assert.equal(await page.locator('#relay-owner-message-form .owner-job-fields').isVisible(),false);assert.equal(await page.locator('#relay-owner-job-project').inputValue(),'');assert.equal(await page.locator('#relay-owner-job-goal').inputValue(),'');assert.equal(await page.locator('#relay-owner-message-text').inputValue(),'');assert.match(await page.locator('#relay-owner-message-form [role=status]').innerText(),/Resolve your unconfirmed send/);assert.equal(phone.records.slice(before).filter(r=>r.path.startsWith('/relay/owner/')).length,0);assert.equal(writes().length,1,'The shortcut cannot create a replacement task or retry automatically');
    const retry=page.getByRole('button',{name:'Retry private send',exact:true});await retry.waitFor();await writeSyntheticEvidence(phone,'private-add-task-unconfirmed-retry',{synthetic:true,originalSendStillRetryable:true,openingRequests:0});
    const confirmed=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/relay/owner/jobs'&&r.ok());await retry.click();await confirmed;await page.waitForFunction(()=>document.querySelector('#relay-owner-message-form [role=status]')?.textContent.includes('Earlier request confirmed'));
    assert.equal(writes().length,2);assert.deepEqual(JSON.parse(writes()[1].body),accepted,'Explicit retry preserves the original UUID, body, title, scope and labels');assert.equal(h.rows('SELECT COUNT(*) AS n FROM relay_owner_jobs')[0].n,2,'Retry cannot create a duplicate task');assert.equal(await page.locator('#relay-owner-message-text').inputValue(),'');assert.equal(await page.locator('#relay-owner-message-form .owner-job-fields').isVisible(),false);
    await add.click();assert.equal(await page.locator('#relay-owner-job-project').inputValue(),'');assert.equal(await page.locator('#relay-owner-job-goal').inputValue(),'');assert.equal(writes().length,2,'After explicit resolution, opening new prefills still does not send');
    await conversationMenu(page,'Public chat');assert.equal((await page.locator('body').innerText()).includes(project),false);assertBrowserContained(phone);await assertNoPrivatePersistence(page,[project,goal,'Fictional uncertain task body']);
  }finally{await closeConversationHarness(browser,h,pages);}
});
