import test from 'node:test';
import assert from 'node:assert/strict';
import {createConversationFixture,launchQualifiedBrowser,openConversationPage,conversationMenu,closeConversationHarness,assertBrowserContained,assertNoPrivatePersistence,writeSyntheticEvidence,RELAY_URL} from './helpers/relay-conversation-browser-fixture.js';
import {RELAY_OWNER_INBOX} from '../backend/relay-common.js';

test('private projects expose truthful current work and corrected results with zero extra expansion requests', {timeout:120000},async t=>{
  const browser=await launchQualifiedBrowser(t);if(!browser)return;const h=createConversationFixture(t),pages=[];
  try{
    const auth=await h.oauth(),owner=await h.pair(auth),rpc=(name,args)=>h.rpc(auth,name,{inbox_id:RELAY_OWNER_INBOX,...args});
    async function create(title,labels=true){const response=await h.phone('/jobs',{id:crypto.randomUUID(),title,body:'Fictional private task: '+title,action_kind:'read_only',...(labels?{project_title:'Fictional garden',goal_title:'Plan a quiet path'}:{})},owner.device_token);assert.equal(response.status,201);return (await response.json()).job;}
    const queued=await create('Compare path materials'),working=await create('Check the two source notes'),blocked=await create('Confirm the path width'),done=await create('Draft the planting list'),unverified=await create('An old acknowledgement',false);
    const workingRun=crypto.randomUUID();await rpc('relay_owner_job_claim',{job_id:working.id,run_id:workingRun,event_id:crypto.randomUUID()});await rpc('relay_owner_job_update',{job_id:working.id,run_id:workingRun,event_id:crypto.randomUUID(),stage:'running',summary:'Read both fictional notes; checking the measurements.'});
    const blockedRun=crypto.randomUUID();await rpc('relay_owner_job_claim',{job_id:blocked.id,run_id:blockedRun,event_id:crypto.randomUUID()});await rpc('relay_owner_job_update',{job_id:blocked.id,run_id:blockedRun,event_id:crypto.randomUUID(),stage:'waiting_for_owner',summary:'Which fictional width should the path use?',outcome:'not_started'});
    const doneRun=crypto.randomUUID();await rpc('relay_owner_job_claim',{job_id:done.id,run_id:doneRun,event_id:crypto.randomUUID()});const reply=await rpc('relay_owner_reply',{message_id:done.id,body:'Fictional original list: three shrubs.'});await rpc('relay_owner_job_update',{job_id:done.id,run_id:doneRun,event_id:crypto.randomUUID(),stage:'completed',summary:'Checked and prepared the fictional planting list.',outcome:'known',expected_reply_id:reply.entry.id,expected_version:1});await rpc('relay_owner_job_result_correct',{job_id:done.id,event_id:crypto.randomUUID(),expected_reply_id:reply.entry.id,expected_version:1,body:'Fictional corrected list: four shrubs. https://example.test/fictional-source',correction_summary:'Checked the fictional second note; corrected the count.'});
    await rpc('relay_owner_reply',{message_id:unverified.id,body:'Fictional acknowledgement: I received this.'});
    const phone=await openConversationPage(browser,h,{owner,clock:false});pages.push(phone);const page=phone.page;
    await page.goto(RELAY_URL);await page.locator('[data-job-id="'+working.id+'"]').waitFor();
    const before=phone.records.filter(r=>r.method==='GET'&&r.path.startsWith('/relay/owner/')).length,beforeAll=phone.records.filter(r=>r.path.startsWith('/relay/owner/')).length;
    const detailReads=()=>phone.records.filter(r=>r.method==='GET'&&r.path.endsWith('/jobs/detail'));
    await conversationMenu(page,'Requests');const work=page.locator('#relay-owner-current-work');await work.waitFor();
    assert.equal(await work.locator('[data-job-id="'+queued.id+'"]').getAttribute('data-state'),'queued');assert.equal(await work.locator('[data-job-id="'+working.id+'"]').getAttribute('data-state'),'working');assert.equal(await work.locator('[data-job-id="'+blocked.id+'"]').getAttribute('data-state'),'blocked');assert.equal(await work.locator('[data-job-id="'+unverified.id+'"]').getAttribute('data-state'),'blocked');
    assert.match(await work.locator('.owner-work-attention').innerText(),/Waiting for you · 1/);assert.match(await work.locator('.owner-work-attention').innerText(),/Completion unverified · 1/);
    await work.locator('#relay-owner-work-filter').selectOption('waiting_for_owner');assert.equal(await work.locator('details[data-job-id]').count(),1);assert.equal(await work.locator('details[data-job-id]').first().getAttribute('data-job-id'),blocked.id);await work.locator('#relay-owner-work-filter').selectOption('all');
    const current=work.locator('[data-job-id="'+working.id+'"]');assert.equal(await current.evaluate(n=>n.open),false);assert.match(await current.locator('summary').first().innerText(),/Read both fictional notes/);assert.match(await work.locator('[data-job-id="'+blocked.id+'"]>summary').innerText(),/Which fictional width/);await current.locator('summary').first().click();assert.match(await current.innerText(),/Read both fictional notes/);
    const waiting=work.locator('[data-job-id="'+blocked.id+'"]');await waiting.locator('summary').first().click();assert.match(await waiting.innerText(),/Which fictional width/);
    await work.locator('.owner-work-finished>summary').click();const finished=work.locator('[data-job-id="'+done.id+'"]');await finished.locator('summary').first().click();assert.match(await finished.innerText(),/Corrected result · version 2/);assert.match(await finished.innerText(),/four shrubs/);assert.match(await finished.innerText(),/reply version 1/);
    await conversationMenu(page,'Search current work');const search=page.getByRole('searchbox',{name:'Search current work'});
    await search.fill('measurements');assert.equal(await work.locator('details[data-job-id]').count(),1);assert.equal(await work.locator('details[data-job-id]').first().getAttribute('data-job-id'),working.id);
    await work.locator('#relay-owner-work-filter').selectOption('queued');assert.equal(await work.locator('details[data-job-id]').count(),0);assert.match(await work.innerText(),/No work matches this search and status/);
    await search.fill('');assert.equal(await work.locator('details[data-job-id]').count(),1);assert.equal(await work.locator('details[data-job-id]').first().getAttribute('data-job-id'),queued.id);
    await work.locator('#relay-owner-work-filter').selectOption('finished');await search.fill('four shrubs');assert.equal(await work.locator('details[data-job-id]').count(),1);assert.equal(await work.locator('details[data-job-id]').first().getAttribute('data-job-id'),done.id);
    await work.locator('#relay-owner-work-filter').selectOption('all');await page.getByRole('button',{name:'Close search',exact:true}).click();assert.equal(await work.locator('details[data-job-id]').count(),5);
    assert.equal(await current.evaluate(n=>n.open),true,'Task expansion survives local search and filter changes');
    assert.equal(phone.records.filter(r=>r.method==='GET'&&r.path.startsWith('/relay/owner/')).length,before,'Opening Projects, Goals and Tasks uses cached change records only');
    assert.equal(phone.records.filter(r=>r.path.startsWith('/relay/owner/')).length,beforeAll,'Expansion also creates no preflight or other API request');
    assert.equal(phone.records.filter(r=>r.path.endsWith('/jobs/detail')).length,0);
    for(const size of [{width:360,height:800},{width:390,height:844},{width:390,height:520}]){
      await page.setViewportSize(size);const geometry=await page.evaluate(()=>({viewport:innerWidth,height:innerHeight,visualHeight:visualViewport?.height,appHeight:document.documentElement.style.getPropertyValue('--app-height'),width:document.documentElement.scrollWidth,composer:document.querySelector('#relay-owner-message-form').getBoundingClientRect().toJSON()}));assert.ok(geometry.width<=geometry.viewport,JSON.stringify({size,geometry}));assert.ok(geometry.composer.bottom<=size.height+1,JSON.stringify({size,geometry}));const targets=await work.locator('summary:visible,button:visible,select:visible').evaluateAll(nodes=>nodes.map(n=>({tag:n.tagName,height:n.getBoundingClientRect().height,width:n.getBoundingClientRect().width})));assert.ok(targets.every(n=>n.height>=48&&n.width>=48),JSON.stringify({size,targets}));await writeSyntheticEvidence(phone,'private-current-work-'+size.width+'x'+size.height,{synthetic:true,extraExpansionRequests:0,detailRequestsBeforeEvidence:0,geometry});
    }
    await page.setViewportSize({width:390,height:844});const detailResponse=page.waitForResponse(r=>r.request().method()==='GET'&&new URL(r.url()).pathname.endsWith('/jobs/detail')&&r.status()===200);await current.getByRole('button',{name:'Evidence and result',exact:true}).click();await detailResponse;await page.locator('#relay-owner-latest-progress').waitFor();assert.match(await page.locator('#relay-owner-latest-progress').innerText(),/Read both fictional notes/);assert.equal(detailReads().length,1);const detailRequests=phone.records.filter(r=>r.path.endsWith('/jobs/detail'));assert.ok(detailRequests.every(r=>['GET','OPTIONS'].includes(r.method)));assert.ok(detailRequests.filter(r=>r.method==='OPTIONS').length<=1,'At most one ordinary CORS preflight accompanies the one exact detail read');
    await page.getByRole('button',{name:'Close private request',exact:true}).click();assert.equal(await current.evaluate(n=>n.open),true,'Expanded task survives opening its evidence');
    const beforeRefresh=phone.records.length,changesResponse=page.waitForResponse(r=>r.request().method()==='GET'&&new URL(r.url()).pathname.endsWith('/jobs/changes')&&r.status()===200);await conversationMenu(page,'Refresh private inbox');await changesResponse;await page.waitForFunction(()=>!document.querySelector('#relay-owner-message-form [role=status]')?.textContent.includes('Refreshing'));assert.equal(await current.evaluate(n=>n.open),true,'Expanded task survives ordinary refresh');assert.ok(phone.records.slice(beforeRefresh).some(r=>r.method==='GET'&&r.path.endsWith('/jobs/changes')&&r.status===200));assert.equal(detailReads().length,1);
    await page.reload();await page.locator('[data-job-id="'+done.id+'"]').waitFor();await conversationMenu(page,'Requests');await page.locator('#relay-owner-current-work .owner-work-finished>summary').click();const reloaded=page.locator('#relay-owner-current-work [data-job-id="'+done.id+'"]');await reloaded.locator('summary').first().click();assert.match(await reloaded.innerText(),/four shrubs/);
    await conversationMenu(page,'Public chat');assert.equal(await page.locator('#relay-owner-current-work:visible').count(),0);assert.equal((await page.locator('body').innerText()).includes('Fictional garden'),false);
    assertBrowserContained(phone);await assertNoPrivatePersistence(page,['Fictional garden','Fictional private task','four shrubs']);
  }finally{await closeConversationHarness(browser,h,pages);}
});


test('phone work rows wrap and preserve focused reading through heartbeat and new saved activity', {timeout:120000},async t=>{
  const browser=await launchQualifiedBrowser(t);if(!browser)return;const h=createConversationFixture(t),pages=[];
  try{
    const auth=await h.oauth(),owner=await h.pair(auth),rpc=(name,args)=>h.rpc(auth,name,{inbox_id:RELAY_OWNER_INBOX,...args}),jobs=[];
    const long='FictionalLongProjectLabel'.repeat(5).slice(0,120);
    for(let i=0;i<12;i++){const response=await h.phone('/jobs',{id:crypto.randomUUID(),title:(i===0?'FictionalLongTaskTitle'.repeat(6).slice(0,120):'Fictional task '+i),body:'Fictional private reading fixture.',action_kind:'read_only',project_title:long,goal_title:long},owner.device_token);assert.equal(response.status,201);jobs.push((await response.json()).job);}
    const target=jobs[4],run=crypto.randomUUID();await rpc('relay_owner_job_claim',{job_id:target.id,run_id:run,event_id:crypto.randomUUID()});await rpc('relay_owner_job_update',{job_id:target.id,run_id:run,event_id:crypto.randomUUID(),stage:'running',summary:'Compared both fictional notes; one measurement still needs checking.'});
    const phone=await openConversationPage(browser,h,{owner,width:360,height:800});pages.push(phone);const page=phone.page;
    await page.goto(RELAY_URL);await page.locator('[data-job-id="'+target.id+'"]').waitFor();await conversationMenu(page,'Requests');const work=page.locator('#relay-owner-current-work'),current=work.locator('[data-job-id="'+target.id+'"]');
    const row=work.locator('[data-job-id="'+jobs[0].id+'"]');await row.locator('summary').first().scrollIntoViewIfNeeded();const geometry=await row.locator('summary').first().evaluate(n=>({width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height,scroll:n.scrollWidth}));assert.ok(geometry.height>=48&&geometry.scroll<=geometry.width+1,JSON.stringify(geometry));
    // Keep a queued task in view while a different task's lease is renewed.
    await row.evaluate(n=>{const panel=n.closest('.messages'),summary=n.querySelector('summary');panel.scrollTop+=summary.getBoundingClientRect().top-panel.getBoundingClientRect().top-24;summary.focus({preventScroll:true});});
    const before=await row.locator('summary').first().evaluate(n=>({offset:n.getBoundingClientRect().top-n.closest('.messages').getBoundingClientRect().top,id:n.id})),activity=await current.locator('.owner-work-time').innerText(),order=await work.locator('details[data-job-id]').evaluateAll(nodes=>nodes.map(n=>n.dataset.jobId));
    await rpc('relay_owner_job_update',{job_id:target.id,run_id:run,event_id:crypto.randomUUID(),stage:'running'});
    let response=page.waitForResponse(r=>r.request().method()==='GET'&&new URL(r.url()).pathname.endsWith('/jobs/changes')&&r.status()===200);await page.clock.fastForward(30000);await response;await page.waitForFunction(()=>!document.querySelector('#relay-owner-message-form [role=status]')?.textContent.includes('Refreshing'));
    assert.deepEqual(await work.locator('details[data-job-id]').evaluateAll(nodes=>nodes.map(n=>n.dataset.jobId)),order,'A heartbeat cannot reorder work');assert.equal(await current.locator('.owner-work-time').innerText(),activity,'A heartbeat cannot advance visible task activity');
    assert.equal(await page.evaluate(()=>document.activeElement.id),before.id);assert.ok(Math.abs((await row.locator('summary').first().evaluate(n=>n.getBoundingClientRect().top-n.closest('.messages').getBoundingClientRect().top))-before.offset)<=1,'Focused reading anchor survives the existing refresh');
    const other=jobs[9],otherRun=crypto.randomUUID();await rpc('relay_owner_job_claim',{job_id:other.id,run_id:otherRun,event_id:crypto.randomUUID()});await rpc('relay_owner_job_update',{job_id:other.id,run_id:otherRun,event_id:crypto.randomUUID(),stage:'running',summary:'Fictional meaningful activity with enough details to wrap across several lines on the narrow phone screen.'});
    response=page.waitForResponse(r=>r.request().method()==='GET'&&new URL(r.url()).pathname.endsWith('/jobs/changes')&&r.status()===200);await page.clock.fastForward(30000);await response;await page.waitForFunction(()=>!document.querySelector('#relay-owner-message-form [role=status]')?.textContent.includes('Refreshing'));
    assert.equal(await page.evaluate(()=>document.activeElement.id),before.id);assert.ok(Math.abs((await row.locator('summary').first().evaluate(n=>n.getBoundingClientRect().top-n.closest('.messages').getBoundingClientRect().top))-before.offset)<=1,'New activity above the focused task preserves its reading position');
    for(const size of [{width:360,height:800},{width:390,height:844},{width:390,height:520}]){await page.setViewportSize(size);const bounds=await page.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth,bottom:document.querySelector('#relay-owner-message-form').getBoundingClientRect().bottom}));assert.ok(bounds.width<=size.width&&bounds.bottom<=size.height+1,JSON.stringify({size,bounds}));}
    assert.equal(phone.records.filter(r=>r.path.endsWith('/jobs/detail')).length,0);assertBrowserContained(phone);await assertNoPrivatePersistence(page,['FictionalLongProjectLabel','Fictional meaningful activity']);
    await writeSyntheticEvidence(phone,'private-work-reading-anchor',{synthetic:true,focusPreserved:true,readingAnchorTolerance:1,heartbeatReordered:false,heartbeatAdvancedActivity:false});
  }finally{await closeConversationHarness(browser,h,pages);}
});
